# deployment.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins-master
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-master
    spec:
      hostname: jenkins-master
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 16Gi          
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home
#            - name: kube-api-access-wzrlr
#              readOnly: true
#              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      serviceAccountName: jenkins-master
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home  # Name of the PVC created earlier
#        - name: kube-api-access-wzrlr
#          projected:
#            sources:
#              - serviceAccountToken:
#        - name: k8s-sidecar
#          image: kiwigrid/k8s-sidecar:1.24.4
#          env:
#            - name: LABEL
#              value: my-jenkins-config
#            - name: FOLDER
#              value: /var/
#          volumeMounts:
#            - name: jenkins-home
#              mountPath: /var/jenkins_home
#            - name: kube-api-access-wzrlr
#              readOnly: true
#              mountPath: /var/run/secrets/kubernetes.io/serviceaccount