apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
spec:
  accessModes:
    - ReadWriteOnce  # Use ReadWriteMany for multiple node read/write access
  resources:
    requests:
      storage: 10Gi  # Requested storage size
  storageClassName: standard  # Name of the storage class (if applicable)